const constants = {
    GET_ALERTMASTER_SUCCESS: "GET_ALERTMASTER_SUCCESS",
    GET_ALERTMASTER_FAIL: "GET_ALERTMASTER_FAIL",

    GET_COMMON_SUCCESS: "GET_COMMON_SUCCESS",
    GET_COMMON_FAIL: "GET_COMMON_FAIL",
    
    INSERT_COMMON_SUCCESS: "INSERT_COMMON_SUCCESS",
    INSERT_COMMON_FAIL: "INSERT_COMMON_FAIL",

    UPDATE_COMMON_SUCCESS: "UPDATE_COMMON_SUCCESS",
    UPDATE_COMMON_FAIL: "UPDATE_COMMON_FAIL",
  };
  
  export default constants;
  